services:
  db:
    image: postgis/postgis:17-3.4
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:5432" 

  backend:
    image: ghcr.io/harryt1/housing-cost-visualizer/backend:latest
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      TRUSTED_ORIGINS: ${TRUSTED_ORIGINS} 
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:5000
    expose:
      - "5000"
    
    
  nginx:
    image: ghcr.io/harryt1/housing-cost-visualizer/nginx-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
  certbot:
    image: certbot/certbot:latest
    restart: "no"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
 
volumes:
  pgdata: