services:
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      TRUSTED_ORIGINS: ${TRUSTED_ORIGINS} 
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:5000
    expose:
      - "5000"
    

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    expose:
      - "3000"
    
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
  certbot:
    image: certbot/certbot:latest
    restart: "no"
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
 
volumes:
  pgdata: