services:
  db:
    image: postgis/postgis:17-3.4
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432" 
    
  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    volumes:
      - ./backend:/src       # Mount source for live reload
    working_dir: /src
    command: dotnet watch run --urls=http://0.0.0.0:5000
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432
      TRUSTED_ORIGINS: ${TRUSTED_ORIGINS}
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:5000"
    

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
  
  nginx:
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      
  certbot: null
 
volumes:
  pgdata: