services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    volumes:
      - ./backend:/backend      # Mount source for live reload
    working_dir: /backend
    command: dotnet watch run --urls=http://0.0.0.0:5000
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      TRUSTED_ORIGINS: ${TRUSTED_ORIGINS}
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:5000"
    

  frontend:
    image: node:24-bullseye
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  
  nginx:
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      
  certbot: null
 
volumes:
  pgdata: