name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set lowercase repository for GHCR
        run: echo "REPOSITORY_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Set image names
        run: |
          echo "NGINXFRONTEND=ghcr.io/$REPOSITORY_LC/nginx-frontend" >> $GITHUB_ENV
          echo "BACKEND=ghcr.io/$REPOSITORY_LC/backend" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag images
        run: |

            docker build -t $NGINXFRONTEND:${{ github.sha }} -t $NGINXFRONTEND:latest ./frontend
            docker build -t $BACKEND:${{ github.sha }} -t $BACKEND:latest ./backend

      - name: Push nginx-frontend and backend images
        run: |
            docker push $NGINXFRONTEND:${{ github.sha }}
            docker push $NGINXFRONTEND:latest
            docker push $BACKEND:${{ github.sha }}
            docker push $BACKEND:latest
