name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag images
        run: |
            FRONTEND=ghcr.io/${{ github.repository }}/frontend
            BACKEND=ghcr.io/${{ github.repository }}/backend

            docker build -t $FRONTEND:${{ github.sha }} -t $FRONTEND:latest ./frontend
            docker build -t $BACKEND:${{ github.sha }} -t $BACKEND:latest ./backend

      - name: Push frontend and backend images
        run: |
            docker push ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
            docker push ghcr.io/${{ github.repository }}/frontend:latest
            docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
            docker push ghcr.io/${{ github.repository }}/backend:latest
