name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FRONTEND: ghcr.io/${{ github.repository.toLowerCase() }}/frontend
      BACKEND: ghcr.io/${{ github.repository.toLowerCase() }}/backend
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag images
        run: |

            docker build -t $FRONTEND:${{ github.sha }} -t $FRONTEND:latest ./frontend
            docker build -t $BACKEND:${{ github.sha }} -t $BACKEND:latest ./backend

      - name: Push frontend and backend images
        run: |
            docker push ghcr.io/$FRONTEND/frontend:${{ github.sha }}
            docker push ghcr.io/$FRONTEND/frontend:latest
            docker push ghcr.io/$BACKEND/backend:${{ github.sha }}
            docker push ghcr.io/$BACKEND/backend:latest
